---
# setup tasks are tasks that need to be run before the very first
# deploy, like making sure the database exists.
- include: setup.yml
  tags:
    - setup

- name: Install packages leihs depends on
  apt: pkg={{ item }} state=present
  with_items:
    - imagemagick
    - libmysqlclient-dev
    - mysql-client

- name: Configure logrotate for leihs
  template: src=logrotate.j2 dest=/etc/logrotate.d/{{ logrotate_filename }}

# deploy only if the vars we need for deployment are set
- include: deploy.yml
  when: version is defined and deploy_to is defined
  tags:
    - deploy

# Seed if this is the first time leihs gets deployed

- name: See if the database has been seeded already
  command: mysql -u {{ mysql_user }} --password={{ mysql_password }} {{ mysql_database }} -e 'select * from users;'
  register: local_users_present
  tags:
    - seed
  when: local_database == True

- name: See if the remote database has been seeded already
  command: mysql -h {{ mysql_host }} -u {{ mysql_user }} --password={{ mysql_password }} {{ mysql_database }} -e 'select * from users;'
  register: remote_users_present
  tags:
    - seed
  when: local_database == False

- include: seed.yml
  when: (local_users_present is defined and local_users_present.stdout == "") or 
    (remote_users_present is defined and remote_users_present.stdout == "")
  tags:
    - seed

- name: Copy script that resets demo instance data
  template: src=reseed_demo_data.sh.j2 dest="{{ deploy_to }}/current/reseed_demo_data.sh" mode=0744 owner="{{ user }}" group="{{ user }}"
  when: demo_instance == True

- name: Install cronjob that resets demo instance data nightly
  cron: user={{ user }} name="Reseed demo instance" minute="15" hour="4" job="{{ deploy_to }}/current/reseed_demo_data.sh"
  when: demo_instance == True

- name: Reset the demo instance to its initial values
  shell: "{{ deploy_to }}/current/reseed_demo_data.sh"
  remote_user: "{{ user }}"
  when: demo_instance == True

- name: Copy script that runs rake leihs:cron via rbenv
  template: src=run_cronjobs.sh.j2 dest="{{ deploy_to }}/current/run_cronjobs.sh" mode=0744 owner="{{ user }}" group="{{ user }}"
  when: demo_instance == False and test_instance == False

- name: Install cronjob that runs rake leihs:cron via rbenv
  cron: user={{ user }} name="Run leihs cronjobs" minute="15" hour="5" job="{{ deploy_to }}/current/run_cronjobs.sh"
  when: demo_instance == False and test_instance == False
